// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseForm: typeof import('./src/components/base-form/baseForm.vue')['default'];
    BaseList: typeof import('./src/components/base-list/base-list.vue')['default'];
    BaseTable: typeof import('./src/components/base-table/base-table.vue')['default'];
    BaseUpload: typeof import('./src/components/base-upload/base-upload.vue')['default'];
    HeaderNav: typeof import('./src/components/headerNav.vue')['default'];
    LeftMenu: typeof import('./src/components/leftMenu.vue')['default'];
    LeftMenuComponent: typeof import('./src/components/leftMenuComponent.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
}
